### ISSUE TITLE
Documentation on build process

### ISSUE THREAD

**Issue by stonemaster** [dlang-tour/bot#2]
Now that the build process has become more complex we need some transparent documentation how everything plays together. There has been an issue where the current process is discussed and we basically need that information e.g. just in this README file (plus a link in the main repo's README).

**Comment by wilzbach** [comment]
> Now that the build process has become more complex we need some transparent documentation how everything plays together. There has been an issue where the current process is discussed and we basically need that information e.g. just in this README file (plus a link in the main repo's README).

Thanks! I added information to the README here and made a [PR](https://github.com/stonemaster/dlang-tour/pull/479) to the main repo. Atm the bot is moderately simple, the only hard thing is to acquire the tokens and setup the automatic deployment on Heroku.
Let me know if this information here is still incomplete as its a bit hard to tell for me as I would know the missing pieces too.

FYI I have also started to add content to the wiki, e.g [how to create a new language repo](https://github.com/stonemaster/dlang-tour/wiki/Adding-a-new-language-repo).

**Comment by wilzbach** [comment]
> Thanks! I added information to the README here and made a PR to the main repo. Atm the bot is moderately simple, the only hard thing is to acquire the tokens and setup the automatic deployment on Heroku.
> Let me know if this information here is still incomplete as its a bit hard to tell for me as I would know the missing pieces too.
> FYI I have also started to add content to the wiki, e.g how to create a new language repo.

I hope that the documentation is acceptable. Otherwise feel free to reopen or open new concrete issues/questions ;-)
